global:
  scrape_interval: 15s  # Default scrape interval for targets.

scrape_configs:
  - job_name: "fastapi"                # Identifier for the FastAPI service
    static_configs:
      - targets:
          - "fastapi_container:8000"  # FastAPI app running on port 8000 in the Docker network
