global:
  scrape_interval: 15s  # Intervalle de scraping pour Prometheus

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['localhost:8000']  # L'API FastAPI s'exécute sur le port 8000 dans le conteneur
